sources:
  - name: Ether-Coin-Flip
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/25902/goerlie-ether-coin-flip/v0.0.1

plugins:
  - pollingLive:
      defaultInterval: 12000